package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	"github.com/SBPH-Matthew/testosterone-tracker/auth"
	"github.com/SBPH-Matthew/testosterone-tracker/graph/model"
	"github.com/SBPH-Matthew/testosterone-tracker/services"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUserInput) (*model.User, error) {
	return r.UsersRepo.CreateUser(input)
}

// CreateLog is the resolver for the createLog field.
func (r *mutationResolver) CreateLog(ctx context.Context, input model.LogInput) (*model.Log, error) {
	if user := auth.ForContext(ctx); user == nil {
		return nil, fmt.Errorf("Access denied")
	}

	panic(fmt.Errorf("not implemented: createlog - createlog"))
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.User, error) {
	if input.Password != input.ConfirmPassword {
		return nil, fmt.Errorf("passwords do not match.")
	}

	dbUser, err := r.UsersRepo.RegisterUser(input)
	if err != nil {
		return nil, err
	}

	gqlUser := &model.User{
		ID:        dbUser.ID,
		FirstName: dbUser.FirstName,
		LastName:  dbUser.LastName,
		Gender:    dbUser.Gender,
		Email:     dbUser.Email,
		Age:       dbUser.Age,
	}

	return gqlUser, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.User, error) {
	// panic(fmt.Errorf("not implemented: Login - login"))
	user, err := r.UsersRepo.GetUserByEmail(input.Email)
	if err != nil {
		return nil, fmt.Errorf("email not found in the databases.")
	}

	if !services.CheckPassword(input.Password, user.Password) {
		return nil, fmt.Errorf("invalid password.")
	}

	token, err := services.GenerateToken(user.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to generate token: %w", err)
	}

	user.Token = &token

	return user, nil
}

// NewLog is the resolver for the newLog field.
func (r *mutationResolver) NewLog(ctx context.Context, input model.LogInput) (*model.Log, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return nil, fmt.Errorf("unauthenticated")
	}

	return r.LogsRepo.CreateLogs(input, user.ID)
}

// MyLogs is the resolver for the myLogs field.
func (r *mutationResolver) MyLogs(ctx context.Context) ([]*model.Log, error) {
	panic(fmt.Errorf("not implemented: MyLogs - myLogs"))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	return r.UsersRepo.GetUsers()
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return nil, fmt.Errorf("unauthenticated")
	}

	return user, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
