# GraphQL schema example
#
# https://gqlgen.com/getting-started/

type User {
    id: ID!
    first_name: String!
    last_name: String!
    gender: String!
    email: String!
    age: Int
    password: String!
    logs: [Log!]!
    token: String
}

input RegisterInput {
    first_name: String!
    last_name: String!
    gender: String!
    email: String!
    age: Int
    password: String!
    confirm_password: String!
}

input LoginInput {
    email: String!
    password: String!
}

type Log {
    id: ID!
    user_id: ID!
    log_date: String!
    energy_level: Int!
    mood: Int!
    libido: Int!
    sleep_hours: Float!
    exercise_minutes: Float!
    stress_level: Int!
    notes: String
    created_at: String!
}

input LogInput {
    energy_level: Int!
    mood: Int!
    libido: Int!
    sleep_hours: Float!
    exercise_minutes: Float!
    stress_level: Int!
    notes: String
}

input NewUserInput {
    first_name: String!
    last_name: String!
    gender: String!
    email: String!
    age: Int
    password: String!
}

type Query {
    users: [User!]!
    me: User

    # user(id: ID!): User
}

type Mutation {
    createUser(input: NewUserInput!): User!
    createLog(input: LogInput!): Log!
    register(input: RegisterInput!): User!
    login(input: LoginInput!): User!

    newLog(input: LogInput!): Log!
    myLogs: [Log!]!
}
