// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Log struct {
	ID              string  `json:"id"`
	UserID          string  `json:"user_id"`
	LogDate         string  `json:"log_date"`
	EnergyLevel     int32   `json:"energy_level"`
	Mood            int32   `json:"mood"`
	Libido          int32   `json:"libido"`
	SleepHours      float64 `json:"sleep_hours"`
	ExerciseMinutes float64 `json:"exercise_minutes"`
	StressLevel     int32   `json:"stress_level"`
	Notes           *string `json:"notes,omitempty"`
	CreatedAt       string  `json:"created_at"`
}

type LogInput struct {
	EnergyLevel     int32   `json:"energy_level"`
	Mood            int32   `json:"mood"`
	Libido          int32   `json:"libido"`
	SleepHours      float64 `json:"sleep_hours"`
	ExerciseMinutes float64 `json:"exercise_minutes"`
	StressLevel     int32   `json:"stress_level"`
	Notes           *string `json:"notes,omitempty"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type NewUserInput struct {
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Gender    string `json:"gender"`
	Email     string `json:"email"`
	Age       *int32 `json:"age,omitempty"`
	Password  string `json:"password"`
}

type Query struct {
}

type RegisterInput struct {
	FirstName       string `json:"first_name"`
	LastName        string `json:"last_name"`
	Gender          string `json:"gender"`
	Email           string `json:"email"`
	Age             *int32 `json:"age,omitempty"`
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirm_password"`
}

type User struct {
	ID        string  `json:"id"`
	FirstName string  `json:"first_name"`
	LastName  string  `json:"last_name"`
	Gender    string  `json:"gender"`
	Email     string  `json:"email"`
	Age       *int32  `json:"age,omitempty"`
	Password  string  `json:"password"`
	Logs      []*Log  `json:"logs"`
	Token     *string `json:"token,omitempty"`
}
