// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewEntryInput struct {
	Level float64 `json:"level"`
	Unit  string  `json:"unit"`
	Date  string  `json:"date"`
	Notes *string `json:"notes,omitempty"`
}

type NewUserInput struct {
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Gender    string `json:"gender"`
	Email     string `json:"email"`
	Age       *int32 `json:"age,omitempty"`
	Password  string `json:"password"`
}

type Query struct {
}

type TestosteroneEntry struct {
	ID    string  `json:"id"`
	User  *User   `json:"user"`
	Level float64 `json:"level"`
	Unit  string  `json:"unit"`
	Date  string  `json:"date"`
	Notes *string `json:"notes,omitempty"`
}

type User struct {
	ID        string `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Gender    string `json:"gender"`
	Email     string `json:"email"`
	Age       *int32 `json:"age,omitempty"`
	Password  string `json:"password"`
}
